services:
  db:
    image: postgis/postgis:16-3.4
    container_name: kulti-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
